version: "3.4"

services:
  server:
    container_name: deephaven
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.deephaven
    environment:
      JAVA_OPTS: -Xmx16g -Dio.deephaven.app.GcApplication.enabled=true
      START_OPS: -Ddeephaven.console.type=python -Ddeephaven.application.dir=/data/storage/app.d
    ports:
      - '10000:10000'
    volumes:
      - ./data:/data/storage
    networks:
      - dhquestnet

# run once on CLI: "docker network create --subnet "192.168.0.0/16" dhquestnet"
networks:
  dhquestnet:
    external: true



