version: "3.4"

services:
  server:
    container_name: dh_server
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.deephaven
    environment:
      JAVA_TOOL_OPTIONS: -Xmx24g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/data/app.d
    ports:
      - '10000:10000'
    volumes:
      - ./data_dh:/data
    networks:
      - dhquestnet

# run once on CLI: "docker network create --subnet "192.168.0.0/16" dhquestnet"
networks:
  dhquestnet:
    external: true



