version: "3.4"

services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: dh_redpanda
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      dhquestnet:
        ipv4_address: 192.168.0.2  # set explicitly

  questdb:
    container_name: dh_questdb
    build:
      context: .
      dockerfile: docker_files/Dockerfile.questdb
    restart: always
    ports:
      - 8812:8812
      - 9000:9000
      - 9009:9009
    volumes:
      - ./data_questdb:/root/.questdb
    networks:
      dhquestnet:
        ipv4_address: 192.168.0.10  # set explicitly

# run once on CLI: "docker network create --subnet "192.168.0.0/16" dhquestnet"
networks:
  dhquestnet:
    external: true



